version: "3"

services:
  web:
    build:
      context: . # where to find the docker file
      dockerfile: Dockerfile.dev # name of the actual docker file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Says: Reference this folder within the container
      - .:/app # Says: For all other files, refer to host OS and map to /app folder
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
